backend:
  name: github
  repo: GoodNovember/royal-mushroom

# publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: page
    label: Pages
    label_singular: Page
    description: These are simple pages
    folder: src/pages/simple-pages
    create: true
    identifier_field: title
    fields:
      - name: kind
        widget: hidden
        default: page

      - name: template
        label: Template
        widget: select
        default: page
        options: 
          - label: "Normal Page"
            value: page
  
      - name: slug
        label: Slug
  
      - name: title
        label: Title

      - name: body
        label: Body
        widget: markdown
      
      - name: tags
        label: Tags
        widget: list
        multiple: true
        required: false

  - name: standard
    label: Educational Standards
    label_singular: Standard
    description: These are Georgia Educational Standards
    folder: src/pages/standards
    identifier_field: title
    create: true
    fields:
      - name: kind
        widget: hidden
        default: standard

      - name: title
        label: Standard Title
        widget: string
        hint: "This describes the Standard, include the code, for example: \"SS1H1 Read about and describe the life of historical figures in American history.\""
    
      - name: class
        label: Class
        widget: select
        default: SS
        options:
          - label: (SS) Social Studies
            value: SS
        hint: Currently, there is only Social Studies currently implemented.

      - name: grade
        label: Grade Level
        widget: select
        default: page
        options:
          - label: (K) Kindergarden
            value: "K"
          - label: (1) 1st Grade
            value: "1"
          - label: (2) 2nd Grade
            value: "2"
          - label: (3) 3rd Grade
            value: "3"
          - label: (4) 4th Grade
            value: "4"
          - label: (5) 5th Grade
            value: "5"
          - label: (6) 6th Grade
            value: "6"
          - label: (7) 7th Grade
            value: "7"
          - label: (8) 8th Grade
            value: "8"
          - label: (9) 9th Grade
            value: "9"
          - label: (10) 10th Grade
            value: "10"
          - label: (11) 11th Grade
            value: "11"
          - label: (12) 12th Grade
            value: "12"

      - name: domain_label
        label: Domain
        widget: select
        options:
          - label: (H) Historical Understandings
            value: H 
          - label: (G) Geographic Understandings
            value: G
          - label: (CG) Government / Civic Understandings
            value: CG
          - label: (E) Economic Understandings
            value: E

      - name: domain_number
        label: Domain Number
        valueType: int
        min: 1
        widget: number
        hint: This represents the last number in the Standard Code

      - name: body
        label: Body
        widget: markdown
        hint: Here you should add the alphabetical list of articles for this standard. I suggest using Markdown Mode and having a blank line in between each entry.

      - name: tags
        label: Tags
        widget: list
        multiple: true
        required: false

  - name: event
    label: Museum Events
    label_singular: Event
    description: These are upcoming events at the museum.
    folder: src/pages/events
    create: true
    fields:
      - name: kind
        widget: hidden
        default: event
      - name: title
        label: Event Title
        widget: string
      - name: slug
        label: Event Slug
        widget: string
        hint: This is the unique url that should point to this event.
      - name: featuredImage
        label: Featured Image
        widget: image
        required: false
      - name: startDateTime
        label: Start Date & Time
        widget: datetime
      - name: endDateTime
        label: End Date & Time
        widget: datetime
      - name: cost
        label: Cost
        hint: How much does the event cost?
        required: false
      - name: ticketURL
        label: Ticket URL
        widget: string
        hint: Leave blank to remove ticket link from event.
        required: false
      - name: location
        label: Location
        widget: string
        required: false
        hint: Leave blank to use the Default Location specified in the Museum Event Settings
      - name: body
        label: Body
        widget: markdown
        hint: The details of the event.
      - name: tags
        label: Tags
        widget: list
        required: false
  
  - name: settings
    label: Settings
    description: Here is where you can edit settings for the website.
    editor:
      preview: false
    files:
      - name: SiteSettings
        label: General Website Settings
        description: Things like the Website Title
        file: "src/data/settings/site/settings.yml"
        fields:
          - name: siteTitle
            label: Site Title
            default: Royal Mushroom
      - name: socialMediaSettings
        label: Social Media Settings
        file: "src/data/settings/socialMedia/settings.yml"
        fields:
          - name: socialMediaTwitterUsername
            label: Twitter Username
            widget: string
      - name: standardSettings
        label: Educational Standard Settings
        file: "src/data/settings/standard/settings.yml"
        fields:
          - name: standardPathPrefix
            label: Educational Standard Prefix
            widget: string
            default: standard
            hint: "Please do not add a slash. Example: www.negahc.org/{path-prefix}/sskh1"
          - name: standardIndexPath
            label: Standard Index Path
            widget: string
            default: standards
            hint: This is where you go when you want to view all the standards.
      - name: eventSettings
        label: Museum Event Settings
        file: "src/data/settings/event/settings.yml"
        fields:
          - name: eventPathPrefix
            label: Event Path Prefix
            widget: string
            default: event
          - name: eventDefaultLocation
            label: Default Event Location
            widget: string
            hint: 322 Academy Street NE Gainesville, GA 30501 
