backend:
  name: github
  repo: GoodNovember/royal-mushroom

media_folder: static/assets
public_folder: assets

collections:
  - name: page
    label: Page
    folder: src/pages/simple-pages
    create: true
    fields:
      - name: template
        label: Template
        widget: select
        default: page
        options: 
          - label: "Normal Page"
            value: page
  
      - name: path
        label: Path
  
      - name: date
        label: Date
        widget: date

      - name: title
        label: Title

      - name: body
        label: Body
        widget: markdown